class AliceGameMadcapPawn extends AliceGameKynapseWalkingPawn
    placeable
    config(Game)
    hidecategories(Navigation);

var(AISphinxAnimIndex) int NockdownIndex;

defaultproperties
{
    NPCAnimationParaConfigs(0)=(AnimationNames=("MadCap_Damaged_Light02"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=0,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Damaged_Light")
    NPCAnimationParaConfigs(1)=(AnimationNames=("MadCap_Damaged_Heave02"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=1,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Damaged_Heave")
    NPCAnimationParaConfigs(2)=(AnimationNames=("MadCap_Nockdown"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=2,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Nockdown")
    NPCAnimationParaConfigs(3)=(AnimationNames=("MadCap_Death02"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=3,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="Madcap_Death")
    NPCAnimationParaConfigs(4)=(AnimationNames=("MadCap_Taunt01","MadCap_Taunt02","MadCap_Taunt03"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=4,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="Madcap_Taunt")
    NPCAnimationParaConfigs(5)=(AnimationNames=("MadCap_Sleep_Idle01","MadCap_Sleep_Idle02","MadCap_Sleep_Idle03"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=5,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="Madcap_Sleep_Idle")
    NPCAnimationParaConfigs(6)=(AnimationNames=("MadCap_WakeUp"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=6,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="Madcap_WakeUp")
    NPCAnimationParaConfigs(7)=(AnimationNames=("MadCap_Talk02"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=7,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="Madcap_Talk")
    NPCAnimationParaConfigs(8)=(AnimationNames=("MadCap_Scare"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=8,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="Madcap_Scare")
    NPCAnimationParaConfigs(9)=(AnimationNames=("MadCap_Flee"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=9,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="Madcap_Flee")
    NPCAnimationParaConfigs(10)=(AnimationNames=("MadCap_GetUp"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=10,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="Madcap_GetUp")
    NPCAnimationParaConfigs(11)=(AnimationNames=("MadCap_Attack_T"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=11,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Attack_T")
    NPCAnimationParaConfigs(12)=(AnimationNames=("MadCap_Warn01"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=12,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Warn01")
    NPCAnimationParaConfigs(13)=(AnimationNames=("MadCap_Warn02"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=13,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Warn02")
    NPCAnimationParaConfigs(14)=(AnimationNames=("MadCap_Warn03"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=14,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Warn03")
    NPCAnimationParaConfigs(15)=(AnimationNames=("MadCap_Attack_Melee01b"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=15,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Attack_Melee01")
    NPCAnimationParaConfigs(16)=(AnimationNames=("MadCap_Attack_Melee02b"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=16,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Attack_Melee02")
    NPCAnimationParaConfigs(17)=(AnimationNames=("MadCap_Attack_Melee03"),BlendNodeIndex="EABLIdx_Slot_FullBody_Main",AnimType=17,BlendInTime=0.2,BlendOutTime=0.2,PlayRate=1.0,bLoop=False,bCauseActorAnimEnd=True,bTriggerFakeRootMotion=False,bNotExtendAnimTimeForFakeRootMotion=False,AnimPlayType="ECAPT_RandomPickupOne",RootBoneTransitionOption="RBA_Default",RootBoneTransitionOption[1]="RBA_Default",RootBoneTransitionOption[2]="RBA_Default",RootBoneRotationOption="RRO_Default",RootBoneRotationOption[1]="RRO_Default",RootBoneRotationOption[2]="RRO_Default",FakeRootMotionMode="RMM_Accel",AnimationDescName="MadCap_Attack_Melee03")
    LightEnvironment="Default__AliceGameMadcapPawn.MyLightEnvironment"
    KynapseHandle="Default__AliceGameMadcapPawn.PawnKynapseHandle"
    Mesh="Default__AliceGameMadcapPawn.DemoPawnSkeletalMeshComponent"
    CylinderComponent="Default__AliceGameMadcapPawn.CollisionCylinder"
    FacialAudioComp="Default__AliceGameMadcapPawn.FaceAudioComponent"
    Components(0)="Default__AliceGameMadcapPawn.CollisionCylinder"
    Components(1)="Default__AliceGameMadcapPawn.Arrow"
    Components(2)="Default__AliceGameMadcapPawn.FaceAudioComponent"
    Components(3)="Default__AliceGameMadcapPawn.MyLightEnvironment"
    Components(4)="Default__AliceGameMadcapPawn.DemoPawnSkeletalMeshComponent"
    Components(5)="Default__AliceGameMadcapPawn.PawnKynapseHandle"
    CollisionComponent="Default__AliceGameMadcapPawn.CollisionCylinder"
}
